# Header Menu
menu:
  Home: /
  Blog: /archives
  GIF: /forframe
  Github: https://github.com/stintosestudios

# disable banner
use_header_cover: true

# URL of the banner image at source/img/
index_cover: /img/banner_320.png

widgets:
- category
- tag
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# favicon
favicon: /favicon.png

# Google Analytics Tracking ID
google_analytics: UA-90092106-1

